v1
LucasCscBks/TM_ToDo pull request #4
Opened 2022-11-22 23:58 UTC by LucasCscBks

Substitui os 2 unwrap que tinha no input e no show_todo! 
Acredito que esteja meio feio o código, mas não to conseguindo pensar em como fazer melhor esse tratamento de erros.

2022-11-23 14:25 UTC, luisholanda reviewed
@LucasCscBks, veja se [essa versão](https://github.com/terramagna/onboarding-rust/blob/refac/clarificar-projeto3/essenciais/1-basico/10-projeto-3/README.md) do projeto deixa mais claro oq é esperado :)

2022-11-27 06:31 UTC, LucasCscBks commented
Removi os unwraps. Ta no caminho? Ou ainda ta longe?

2022-11-28 12:18 UTC, luisholanda requested changes
A maior parte da _lógica_ está ok, mas podemos melhorar bastante o código. Tente usar `?` e [`.map_err`](https://doc.rust-lang.org/std/result/enum.Result.html#method.map_err) para simplificar o código.

2022-11-28 12:18 UTC, luisholanda commented on src/main.rs
> +            Err(error) => Err(error)
`Err(error)` aqui não tem nenhum efeito. Como estamos na main, você precisa implementar alguma lógica para reportar o erro ao usuário.

2022-11-30 16:49 UTC, lffg commented on src/main.rs
> +    Stdin(String),
Hmm, por que você está armazenando a mensagem do `io::Error` aqui? Que tipo de informação essas strings adicionam aqui?

Na minha opinião, para esses dois casos de erro, _apenas_ a variante (e.g. `Stdout` ou `Stdin`) já são suficientes neste caso.

Agora em um erro como `FileNotFound(String)`, a `String` ali dentro seria interessante para que, por exemplo, pudéssemos armazenar o _caminho_ do arquivo que não foi encontrado, entende?

Nesses casos, apenas com a variante `Stdout` e `Stdin` você já consegue dar mensagens de erro relativamente precisas ao usuário, por exemplo: "não foi possível imprimir o texto na tela" e "não foi possível ler o texto", respectivamente. Aí você só faz essa "tradução" da variante para a mensagem de diagnóstico perto da `main`, que é onde você faz o _report_.

O que acha?

2022-11-30 16:49 UTC, lffg commented on src/main.rs
> +        let res = self.input()?;
Ótimo uso da interrogação aqui! 😃

2022-11-30 18:15 UTC, luisholanda commented on src/main.rs
> +            Err(error) => Err(TerminalError::Stdin(format!("Erro {:?}", error)))
Você não acha estranho essa função ter que se preocupar com formatação do erro? Acho que o ideal seria `TerminalError` armazenar o erro e ter algum método responsável por emitir a mensagem da forma que você deseja. Isso centraliza a responsabilidade de formatação dos erros.

2022-12-05 15:32 UTC, luisholanda approved these changes
Só uma sugestão final, de resto LGTM.

2022-12-05 15:32 UTC, luisholanda commented on src/main.rs
> +        }
Dá uma olhada no método `map_err` de `Result`, vai simplificar bastante esse código :)

2022-12-06 21:11 UTC, merged