new methods, todos module, vec crud
LucasCscBks/TM_ToDo pull request #6
Opened 2022-12-26 22:18 UTC by LucasCscBks

Implementei o novo modulo de armazenar todos os TODOS, fiz utilizando vec e consegui implementar pra listar, adicionar, atualizar e deletar os todos.

2023-01-02 18:58 UTC, luisholanda commented on src/terminal.rs
> +                        todo_collection.todos[number - 1] = Todo::new(todo);
N acho que seja responsabilidade dessa parte do código saber como atualizar o todo. Isso deveria estar em um método em `Todos`.

2023-01-02 18:58 UTC, luisholanda commented on src/terminal.rs
> +                        todo_collection.todos.remove(number - 1);
Mesma coisa aqui.

2023-01-02 23:13 UTC, LucasCscBks commented
Atualizei os métodos update e delete colocando dentro da estrutura Todos e usei o clearscreen pra limpar o console pra mostrar de uma forma mais limpa as informaçoes.

2023-01-05 13:15 UTC, luisholanda requested changes

2023-01-05 13:15 UTC, luisholanda commented on src/terminal.rs
> +    fn system_options(&mut self) -> Result<String, TerminalError> {
Ao invés de retornar uma string, sugiro criar um enum que deixe explicito quais os comandos possíveis. Isso facilita muito o uso pelas camadas superiores.

2023-01-05 13:15 UTC, luisholanda commented on src/terminal.rs
> +                        todo_collection.remove_todo(number);
Ao invés de termos que fazer esse check aqui, o ideal seria `remove_todo` lidar com isso. Você pode fazer ele retornar `Option<Todo>` para conseguir diferenciar quando ele conseguiui remover e quando não.

2023-01-05 13:15 UTC, luisholanda commented on src/terminal.rs
> +                    if number > todo_collection.todos.len() || number == 0 {
Aqui o caso é um pouco diferente da remoção pois só podemos perguntar o novo TODO se ele existir, mas conseguimos melhorar criando um método `todo_collection.get_todo(number)` que retornar `Option<&Todo>`, aí conseguimos saber se o todo existe ou não.

2023-01-05 13:15 UTC, luisholanda commented on src/todos.rs
> +    pub todos: Vec<Todo>,
O objetivo dessa struct é camadas superiores não terem que manipular esse vec diretamente, então esse campo tem que ser privado.

2023-01-05 13:15 UTC, luisholanda commented on src/terminal.rs
> +            if todo_collection.todos.len() > 0 {
Que tal um `todo_collection.is_empty()`?

2023-01-05 23:44 UTC, LucasCscBks commented on src/terminal.rs
> +                        todo_collection.remove_todo(number);
Não entendi muito bem essa parte de retornar o Option<Todo>, mas trasnferi o check pra função remove.

2023-01-06 00:43 UTC, LucasCscBks commented
Fiz as alterações. !!!

2023-01-10 13:55 UTC, luisholanda commented on src/todos.rs
> +    pub fn show_todos(&mut self) {
Não acho que seja responsabilidade dessa struct mostrar mensagens na tela. Como você acha que conseguiriamos implementar uma operação em `Todos` que permitisse que uma camada superior conseguisse implementar a lógica de listar os todos?

2023-01-10 13:55 UTC, luisholanda commented on src/todos.rs
> +    pub fn remove_todo(&mut self, index:usize) {
Mesma coisa do `show_todos` aqui.

2023-01-10 13:55 UTC, luisholanda commented on src/terminal.rs
>  pub fn loop_todo() -> Result<(), TerminalError> {
Nessa função vejo o mesmo problema que há na struct `Todos`: não está claro a responsabilidade de quem tem que mostrar mensagens na tela. Essa responsabilidade é de `Terminal` certo?

2023-01-11 05:09 UTC, LucasCscBks commented on src/terminal.rs
>  pub fn loop_todo() -> Result<(), TerminalError> {
Não entendi qual a parte que você quer que eu modifique aqui!
Poderia esclarecer melhor por gentileza? :D

2023-01-12 03:20 UTC, LucasCscBks commented
Atualizei o que foi pedido! Acho que está correto!

2023-01-17 16:51 UTC, luisholanda commented on src/terminal.rs
>  pub fn loop_todo() -> Result<(), TerminalError> {
Estou me referindo aos `println!` e, com um pouco de preciosismo, o uso de `style`, mas para esse projeto podemos focar nos `println!`s. Que tal adicionar um `show_error_message`?

2023-01-18 19:23 UTC, LucasCscBks commented on src/terminal.rs
>  pub fn loop_todo() -> Result<(), TerminalError> {
Certo, Feito!

2023-01-19 13:47 UTC, luisholanda approved these changes

2023-01-19 16:08 UTC, merged